int friends = 10;
//friends = friends + 2;
//friends++;
//friends = friends - 1;
//friends--;
//friends = friends * 5;
//friends --;
//friends = friends / 2;
//friends--;
Console.WriteLine(friends);
Console.ReadKey();
